### PR TITLE
Fix italicizing for multiline props #54

### PR DESCRIPTION
**Pull request by azranel**
Slack doesn't handle single italization for multi line text. This means we need to italicize each line in multi line prop.

Related issue: https://github.com/netguru/props/issues/54

### CODE REVIEW

**Comment by lubieniebieski** [comment]
how about a spec?:)

**Comment by lubieniebieski** [comment]
`bin/guard` turned on during implementation?:)

**Comment by azranel** [comment]
@lubieniebieski of course! :smile: When I saw what it can do, I started using it immediately.

**Comment by lubieniebieski** [comment]
👍 💙

**Pull request merged**
